### ISSUE TITLE
Fix UI

### ISSUE THREAD

**Issue by BernabeFelix** [BernabeFelix/todalasemana2.0#54]
The new promotion single result looks broken
<img width="426" alt="screen shot 2018-04-17 at 11 24 38 pm" src="https://user-images.githubusercontent.com/7790491/38912167-6e42681c-4299-11e8-820f-8e8739235d2c.png">
1. The image needs to respect margins/paddings
2. Title and category need to be horizontally aligned or remove category
<img width="406" alt="screen shot 2018-04-17 at 11 24 50 pm" src="https://user-images.githubusercontent.com/7790491/38912206-9b6e515c-4299-11e8-907e-cf4abb86514b.png">
3. Share button should not touch the image (10 px or so of space).
4. Add a max height of 250 px. The promotion is all expanded because of the markup and the image is just 300px height.
<img width="1280" alt="screen shot 2018-04-18 at 12 05 18 am" src="https://user-images.githubusercontent.com/7790491/38912673-3d22a866-429c-11e8-9d51-f77b175ae9a6.png">

The markup is not good, everything should be in either a row or a 12-column to mantain spaces working.

**Comment by paulsancer** [comment]
progress in pr #53

**Comment by paulsancer** [comment]
Completed in PR #53, please validate
