### ISSUE TITLE
Fix Facebook Share

### ISSUE THREAD

**Issue by BernabeFelix** [BernabeFelix/todalasemana2.0#72]

**Comment by paulsancer** [comment]
@BernabeFelix I don't see any bug with facebook share, please elaborate...

**Comment by BernabeFelix** [comment]
<img width="1016" alt="screen shot 2018-04-22 at 9 50 40 pm" src="https://user-images.githubusercontent.com/7790491/39104734-4a738218-4677-11e8-974d-8428053b365e.png">

**Comment by paulsancer** [comment]
Fixed, sorry, didn't realize you meant in the server...

**Comment by Polkien** [comment]
Please validate and close.
